window.data = {
  leaguesData: {
  للأندية": {
    logo: "https://imgs.ysscores.com/championship/150/571733336684.png",
    matches: [

{team1: "الأهلي", team2: "إنتر ميامي",
gmtTime: "2025-06-15T00:00:00Z"},

{team1: "بايرن ميونخ", team2: "أوكلاند سيتي",
gmtTime: "2025-06-15T00:00:00Z"},

{team1: "باريس", team2: "أتلتيكو مدريد",
gmtTime: "2025-06-15T00:00:00Z"},

{team1: "تشيلسي", team2: "لوس أنجلوس",
gmtTime: "2025-06-16T00:00:00Z"},

{team1: "بوتافوغو", team2: "سياتل",
gmtTime: "2025-06-16T00:00:00Z"},

{team1: "بالميراس", team2: "بورتو",
gmtTime: "2025-06-16T00:00:00Z"},

{team1: "سياتل",team2: "باريس",
gmtTime: "2025-06-23T19:00:00Z",  url: "go:s"},

{team1: "أتلتيكو مدريد",team2: "بوتافوغو",
gmtTime: "2025-06-23T19:00:00Z",  url: "go:s"},

{team1: "بورتو",team2: "الأهلي",
gmtTime: "2025-06-24T01:00:00Z",  url: "go:s"},

{team1: "إنتر ميامي",team2: "بالميراس",
gmtTime: "2025-06-24T01:00:00Z",  url: "go:s"},

{team1: "بنفيكا",team2: "بايرن ميونخ",
gmtTime: "2025-06-24T19:00:00Z",  url: "go:s"},

{team1: "أوكلاند سيتي",team2: "بوكا جونيورز",
gmtTime: "2025-06-24T19:00:00Z",  url: "go:s"},

{team1: "الترجي",team2: "تشيلسي",
gmtTime: "2025-06-25T01:00:00Z",  url: "go:s"},

{team1: "لوس أنجلوس",team2: "فلامنجو",
gmtTime: "2025-06-25T01:00:00Z",  url: "go:s"},

{team1: "صن داونز",team2: "فلومنينسي",
gmtTime: "2025-06-25T19:00:00Z",    url: "go:s"},

{team1: "دورتموند",team2: "أولسان",
gmtTime: "2025-06-25T19:00:00Z",   url: "go:s"},

{team1: "إنتر ميلان",team2: "ريفر بليت",
gmtTime: "2025-06-26T01:00:00Z",   url: "go:s"},

{team1: "أوراوا رد",team2: "مونتيري",
gmtTime: "2025-06-26T01:00:00Z",   url: "go:s"},

{team1: "يوفنتوس",team2: "مانشستر سيتي",
gmtTime: "2025-06-26T19:00:00Z", url: "go:s" },

{team1: "الوداد",team2: "العين",
gmtTime: "2025-06-26T19:00:00Z",  url: "go:s" },

{team1: "سالزبورج",team2: "الريال",
gmtTime: "2025-06-27T01:00:00Z",  url: "go:s" },

{team1: "الهلال",team2: "باتشوكا",
gmtTime: "2025-06-27T01:00:00Z",   url: "go:s" },

{team1: "بالميراس",team2: "بوتافوغو",
gmtTime: "2025-06-28T16:00:00Z",  url: "go:s"  },

{team1: "بنفيكا",team2: "تشيلسي",
gmtTime: "2025-06-28T20:00:00Z",  url: "go:s"},

{team1: "باريس",team2: "إنتر ميامي",
gmtTime: "2025-06-29T16:00:00Z",   url: "go:s"},

{team1: "فلامنجو",team2: "بايرن ميونخ",
gmtTime: "2025-06-29T20:00:00Z",  url: "go:s" },

{team1: "إنتر ميلان",team2: "فلومنينسي",
gmtTime: "2025-06-30T19:00:00Z",    url: "go:s"},

{team1: "السيتي",team2: "الهلال",
gmtTime: "2025-07-01T01:00:00Z",   url: "go:s" },

{team1: "ريال مدريد",team2: "يوفنتوس",
gmtTime: "2025-07-01T19:00:00Z",  url: "go:s"},

{team1: "دورتموند",team2: "مونتيري",
gmtTime: "2025-07-02T01:00:00Z",  url: "go:s"},

{team1: "بالميراس",team2: "تشيلسي",
gmtTime: "2025-07-05T01:00:00Z",  url: "go:s"},

{team1: "باريس",team2: "بايرن ميونخ",
gmtTime: "2025-07-05T16:00:00Z",  url: "go:s"},

{team1: "فلومنينسي",team2: "الهلال",
gmtTime: "2025-07-04T19:00:00Z", url: "go:s"},

{team1: "ريال مدريد",team2: "دورتموند",
gmtTime: "2025-07-05T20:00:00Z", url: "go:s"},

{team1: "فلومنينسي",team2: "تشيلسي",
gmtTime: "2025-07-08T19:00:00Z", url: "go:s"},

{team1: "باريس",team2: "ريال مدريد",
gmtTime: "2025-07-09T19:00:00Z", url: "go:s"},

{team1: "تشيلسي",team2: "باريس",
gmtTime: "2025-07-13T19:00:00Z", url: "go:s"},
  

  },

  clubsData: {

"كاسا بيا": "https://i.ibb.co/PZj3c261/Cac.png",
"أوزبكستان": "https://cdn.countryflags.com/thumbs/uzbekistan/flag-3d-round-500.png",
"طاجيكستان": "https://cdn.countryflags.com/thumbs/tajikistan/flag-3d-round-500.png",
"كوريا ش": "https://cdn.countryflags.com/thumbs/north-korea/flag-3d-round-250.png",
"هندوراس": "https://cdn.countryflags.com/thumbs/honduras/flag-3d-round-250.png",
"السلفادور": "https://cdn.countryflags.com/thumbs/el-salvador/flag-3d-round-250.png",
"هايتي": "https://cdn.countryflags.com/thumbs/haiti/flag-3d-round-250.png",
"فيجي": "https://cdn.countryflags.com/thumbs/fiji/flag-3d-round-500.png",
"كوستاريكا": "https://i.ibb.co/N6SWLCjw/costa-rica.png",
"يوفينتود": "https://i.ibb.co/JZNJB8S/JUV.png",
"سيارا": "https://i.ibb.co/WWwYc1TR/CEA.png",
"الصفاقسي": "https://www6.0zz0.com/2022/04/28/23/942484437.png",
"بشكتاش": "https://i.ibb.co/jyWdKTy/BJK.png",
"غيماريش": "https://i.ibb.co/GzDcCrH/GIM.png",
"ميراسول": "https://i.ibb.co/SXhbbT2f/MIR.png",
"روفرز": "https://i.ibb.co/d4TmyS4c/ROV.png",
"طرابزون": "https://i.ibb.co/fd1nJcgh/TAR.png",
"دوسلدورف": "https://i.ibb.co/5xfM6yGz/FDS.png",
"بادربورن": "https://i.ibb.co/zWSqCWHh/PAD.png",
"ألفيركا": "https://i.ibb.co/ynHGRgkS/FCA.png",
"سانتوس": "https://i.ibb.co/MxKRYyxf/SFC.png",
"ريكسهام": "https://i.ibb.co/HfWm49g8/REX.png",
"هولشتاين": "https://i.ibb.co/8g9ZK5xZ/HOL.png",
"كارلسروهر": "https://i.ibb.co/kVsVdzDJ/KAR.png",
"كارديف": "https://i.ibb.co/4nL2stVy/CAR.png",
"إنيرجي": "https://i.ibb.co/27NhZg5V/ENE.png",
"ويكومب": "https://i.ibb.co/8T0KHnk/Wyc.png",
"براغانتينو": "https://i.ibb.co/NnCKtHLq/BRT.png",
"بورتوريكو": "https://cdn.countryflags.com/thumbs/puerto-rico/flag-3d-round-250.png",
"النجم الساحلي": "https://www3.0zz0.com/2022/03/19/02/820194712.png",
"شكينديا": "https://i.ibb.co/jkSq7qBL/SHK.png",
"نيقوسيا": "https://i.ibb.co/dwd78L9s/NIC.png",
"بياليستوك": "https://i.ibb.co/k6wnXKLb/BIA.png",
"هامرون": "https://i.ibb.co/sd9ngq84/HAM.png",
"زرينيسكي": "https://i.ibb.co/wZBXcQQr/ZRI.png",
"بالوسبور": "https://i.ibb.co/hqBBKLB/PAL.png",
"لينكولن ريد": "https://i.ibb.co/tMTzTTzF/RED.png",
"دريتا": "https://i.ibb.co/TxFkzjj9/DRI.png",
"لوزان": "https://i.ibb.co/N2r87BMt/LAU.png",
"نوح": "https://i.ibb.co/KcgmQfVZ/NOAH.png",
"بريدابليك": "https://i.ibb.co/chP3GgMY/BRE.png",
"رييكا": "https://i.ibb.co/n84tmBnZ/RIJ.png",
"كييف": "https://i.ibb.co/PsqpP0cC/DYN.png",
"ليخ بوزنان": "https://i.ibb.co/v4nTvDw7/LECH.png",
"رابيد فيينا": "https://i.ibb.co/0ptXpmsH/RAP.png",
"سيليي": "https://i.ibb.co/tT5WzDMZ/NOG.png",
"أبردين": "https://i.ibb.co/vxD82N1c/ABE.png",
"شاختار": "https://i.ibb.co/jPwQdWmY/SHA.png",
"راكوف": "https://i.ibb.co/ZndZ6z8/RAK.png",
"كرايوفا": "https://i.ibb.co/zpKT6ZV/CRA.png",
"آيك لارناكا": "https://i.ibb.co/CK9QP1BZ/AEK.png",
"شيلبورن": "https://i.ibb.co/99rLFPGH/SHE.png",
"هاكن": "https://i.ibb.co/W45nqt18/HACK.png",
"سيغما": "https://i.ibb.co/j900Kcdz/SIG.png",
"براتيسلافا": "https://i.ibb.co/0jkkYgcS/BRA.png",
"سامسون": "https://i.ibb.co/b5gFLGgL/SAM.png",
"ليجيا وارسو": "https://i.ibb.co/WNwytBH7/LEG.png",
"سبارتا براغ": "https://i.ibb.co/S4tXMFYx/SPA.png",
"شامروك": "https://i.ibb.co/214GTwX1/SHAM.png",
"أيك أثينا": "https://i.ibb.co/nsJD4ps/AEK-fc.png",
"باوك": "https://i.ibb.co/9m2sXjKk/PAW.png",
"النهضة": "https://i.ibb.co/NdYr19Hj/NAH.png",
"التضامن": "https://i.ibb.co/zVvFQ2qr/HAD.png",
"زاخو": "https://i.ibb.co/m5hpgcDz/ZAK.png",
"سترة": "https://i.ibb.co/H3BpF92/SIT.png",
"القـادسية": "https://www9.0zz0.com/2022/03/17/08/324135061.png",
"بشكتاش": "https://i.ibb.co/jyWdKTy/BJK.png",
"كوجالي": "https://i.ibb.co/YMzRDg0/KOJ.png",
"أروكا": "https://i.ibb.co/fDxVsLN/Arouca.png",
"باهيا": "https://i.ibb.co/VGxX5h6/BAH.png",
"أنطاليا": "https://i.ibb.co/B5LxKMv3/ANT.png",
"كروزيرو": "https://i.ibb.co/VWStFHQn/CRO.png",
"فاسكو": "https://i.ibb.co/r2BKCqzY/FAS.png",
"ألانيا سبورت": "https://i.ibb.co/RdhKVy9/ALA.png",
"فيسينتي": "https://i.ibb.co/GfH6d7LK/GVFC.png",
"بروميتش": "https://i.ibb.co/RGXFzw8N/BRO.png",
"أتلانتا": "https://i.ibb.co/FLgczhjg/ATA.png",
"لانوس": "https://i.ibb.co/C58SnRLg/Lan.png",
"أليانزا ليما": "https://i.ibb.co/S7JY71FY/Ali.png",
"جامعة تشيلي": "https://i.ibb.co/TBdhYbPz/Tch.png",
"بوليفار": "https://i.ibb.co/TxMgJW0R/Bol.png",
"أونس كالداس": "https://i.ibb.co/dJxf0vn2/Ons.png",
"أتلتيكو مينيرو": "https://i.ibb.co/8nNPtYpV/Min.png",
"إنديبندينتي": "https://i.ibb.co/21gvcwQV/Ind.png",
"فينيسا": "https://i.ibb.co/Xr3c9H6b/Vini.png",
"براغا": "https://i.ibb.co/xHS13Dn/BRAGA.png",
"زفيزدا": "https://www14.0zz0.com/2022/03/17/08/608043530.png",
"بوخارست": "https://i.ibb.co/SXs2CCSm/Boc.png",
"بران": "https://i.ibb.co/tPFNJNRf/Bra.png",
"برادفورد": "https://i.ibb.co/YFYSv8dH/Ban.png",
"هدرسفيلد": "https://i.ibb.co/4gY7d5b1/Hud.png",
"دونكاستر": "https://i.ibb.co/QBCs60f/Don.png",
"لودوجوريتس": "https://i.ibb.co/rKkqjr9M/Lud.png",
"جينك": "https://i.ibb.co/Zzwxh0St/Gen.png",
"فيكتوريا": "https://i.ibb.co/4nGqMPLx/Vik.png",
"فرينكفاروزي": "https://i.ibb.co/MDT9rp4F/Fer.png",
"باناثينايكوس": "https://i.ibb.co/HD72t90f/Pan.png",
"يانغ بويز": "https://i.ibb.co/C5bG5j3d/Boys.png",
"مالمو": "https://i.ibb.co/kgy1fPHv/Mal.png",
"زغرب": "https://i.ibb.co/FkNbkpzq/Zag.png",
"ميتييلاند": "https://i.ibb.co/0p3P4q9X/Mid.png",
"بورت فايل": "https://i.ibb.co/QjPqN72j/Port.png",
"سارسفيلد": "https://i.ibb.co/V068fFBp/Sar.png",
"راسينغ": "https://i.ibb.co/DPxyZNxV/Rac.png",
"ساوثهامبتون": "https://i.ibb.co/1tpyWTx5/Sou.png",
"بارنسلي": "https://i.ibb.co/dwXKQ09Q/Bar.png",
"كامبريدج": "https://i.ibb.co/svhhDsT3/Cam.png",
"لينكولن": "https://i.ibb.co/TqW2ZC2Y/Lin.png",
"فروزينوني": "https://i.ibb.co/VWgYjD5M/Fro.png",
"باليرمو": "https://i.ibb.co/m5qnyk4y/Psl.png",
"بيزا": "https://i.ibb.co/JwSsp6nR/PIS.png",
"لاتسيو": "https://www12.0zz0.com/2022/04/24/02/220461122.png",
"تورينو": "https://i.ibb.co/3ky9NKd/TORINO.png",
"ساسولو": "https://i.ibb.co/zJt4htW/Sassuolo.png",
"روما": "https://i.ibb.co/mC2TskWV/ROM.png",
"بارما": "https://i.ibb.co/QjPn4pRc/PAR.png",
"فوتبول": "https://i.ibb.co/s9D333qQ/FOT.png",
"شيفيلد": "https://i.ibb.co/vvQm5WT3/SHE.png",
"بولونيا": "https://i.ibb.co/GQpsZrh4/BFC.png",
"كوفنتري": "https://i.ibb.co/ynFw7VTb/COV.png",
"أودينيزي": "https://i.ibb.co/v4TPPVNv/UDI.png",
"إستوديانتيس": "https://i.ibb.co/mFqDT6pf/Ede.png",
"ليتشي": "https://i.ibb.co/G9kLyxC/LECCE.png",
"كالياري": "https://i.ibb.co/0JJhc71/CAGLIARI.png",
"ساو باولو": "https://i.ibb.co/CKgzTNJV/SPF.png",
"كيتو": "https://i.ibb.co/KJhWdTf/Kito.png",
"الزوراء": "https://i.ibb.co/tMDrc17R/ZAW.png",
"سوانزي": "https://i.ibb.co/Kp8z0xJW/SWA.png",
"إيسترن": "https://i.ibb.co/twkz6Kvd/EAS.png",
"نام دين": "https://i.ibb.co/sv0pDkNJ/NAM.png",
"أركاداغ": "https://i.ibb.co/502RmJF/ARK.png",
"راتشابوري": "https://i.ibb.co/7d1GdHnW/RAT.png",
"أنديجان": "https://i.ibb.co/8gGxsJwp/AND.png",
"غوا": "https://i.ibb.co/hRgm4ghw/GOA.png",
"الخالدية": "https://i.ibb.co/6cpXQY0v/KHD.png",
"تامبينس": "https://i.ibb.co/4RzjWNw2/TAM.png",
"كايا": "https://i.ibb.co/rRGqvXmv/KAY.png",
"بانكوك": "https://i.ibb.co/RpcgnFvc/BAN.png",
"سيلانغور": "https://i.ibb.co/ZRkb887K/SIL.png",
"ماكارثر": "https://i.ibb.co/ycVjfFZ3/MAK.png",
"تاي بو": "https://i.ibb.co/fzsbDvBx/TAI.png",
"ستيلرز": "https://i.ibb.co/7J3ds756/STE.png",
"باثوم": "https://i.ibb.co/27GnZVXk/PAT.png",
"بيرسيب": "https://i.ibb.co/2YthVkzv/PER.png",
"ليون سيتي": "https://i.ibb.co/TqR3S9D3/LIO.png",
"بكين": "https://i.ibb.co/GfzCmsYw/PIK.png",
"كونغ آن": "https://i.ibb.co/mCKtHv8M/CON.png",
"غامبا أوساكا": "https://i.ibb.co/mC0wF2K2/GAM.png",
"ميلوول": "https://i.ibb.co/Vc8zBF9Q/MIL.png",
"جنوى": "https://i.ibb.co/hFMqSV7H/Gen.png",
"هيلاس": "https://i.ibb.co/NVxHq7n/Hellas-Verona.png",
"كومو": "https://i.ibb.co/JLTNPyH/COMO.png",
"الحسين": "https://i.ibb.co/WWrNdnFS/HOS.png",
"المحرق": "https://i.ibb.co/v6hzqx74/MHK.png",
"إستقلال": "https://i.ibb.co/cHgmSDJ/EST.png",
"آهال": "https://i.ibb.co/BVDhrbVD/AHA.png",
"موهون": "https://i.ibb.co/R4j04dc9/MOH.png",
"كريمونيسي": "https://i.ibb.co/zhf8Z2PF/CRE.png",
"دوشنبه": "https://i.ibb.co/zTPb6CQB/IST.png",
"الوحدات": "https://i.ibb.co/FbMC5RJ4/WAH.png",
"ملبورن": "https://i.ibb.co/xK66rdRw/MEL.png",
"هيروشيما": "https://i.ibb.co/qYF08jmS/HIR.png",
"سيول": "https://i.ibb.co/G3tcTY42/SEO.png",
"ماتشيدا": "https://i.ibb.co/20QCKyxK/ZEL.png",
"شانغهاي": "https://i.ibb.co/s90kHMXv/CFC.png",
"غانغون": "https://i.ibb.co/GvBLKVrX/GAN.png",
"تراكتور": "https://i.ibb.co/8L0WVPX2/TRA.png",
"بوريرام": "https://i.ibb.co/F2B65SQ/BUR.png",
"بورت": "https://i.ibb.co/HTrWSx3b/SIP.png",
"جوهور": "https://i.ibb.co/s9xD7M1G/JOH.png",
"تشنغدو": "https://i.ibb.co/KzxgB8tT/CHE.png",
"فيسيل": "https://i.ibb.co/zhCwVTvp/VIS.png",
"الشرطة": "https://i.ibb.co/x8167H89/SHO.png",
"ناساف": "https://i.ibb.co/MyM2YRvW/NAS.png",
"فيورنتينا": "https://i.ibb.co/s9JHnWgP/Fio.png",
"الدومينيكان": "https://cdn.countryflags.com/thumbs/dominican-republic/flag-3d-round-500.png",
"أندونيسيا": "https://cdn.countryflags.com/thumbs/monaco/flag-3d-round-500.png",
"إندونيسيا": "https://cdn.countryflags.com/thumbs/monaco/flag-3d-round-500.png",
"نيوزيلندا": "https://cdn.countryflags.com/thumbs/new-zealand/flag-3d-round-500.png",
"بنما": "https://cdn.countryflags.com/thumbs/panama/flag-3d-round-500.png",
"أستراليا": "https://cdn.countryflags.com/thumbs/australia/flag-3d-round-500.png",
"كوريا ج": "https://cdn.countryflags.com/thumbs/south-korea/flag-3d-round-500.png",
"اليابان": "https://cdn.countryflags.com/thumbs/japan/flag-3d-round-500.png",
"كوبا": "https://cdn.countryflags.com/thumbs/cuba/flag-3d-round-500.png",
"كاليدونيا": "https://cdn.countryflags.com/thumbs/new-caledonia/flag-3d-round-500.png",
"روسيا": "https://s3.eu-west-2.amazonaws.com/qmasters/flags/png/russia/flag-3d-round-250.png",
"كندا": "https://cdn.countryflags.com/thumbs/canada/flag-3d-round-500.png",
"النرويج": "https://cdn.countryflags.com/thumbs/norway/flag-3d-round-500.png",
"رومانيا": "https://cdn.countryflags.com/thumbs/romania/flag-3d-round-500.png",
"سلافيا براغ": "https://i.ibb.co/VY35qft7/SLA.png",
"أتالانتا": "https://i.ibb.co/FLgczhjg/ATA.png",
"أولمبياكوس": "https://i.ibb.co/d0YcwRCp/OLA.png",
"بافوس": "https://i.ibb.co/CKL28fML/BAF.png",
"غلطة سراي": "https://i.ibb.co/K7vqsSy/Galatasaray.png",
"قره باغ": "https://i.ibb.co/KLbjRBc/QARABAG.png",
"نابولي": "https://i.ibb.co/mVmt2Jvt/NAP.png",
"سان جيلواز": "https://i.ibb.co/bgvT1ZDP/USG.png",
 "برمنغهام": "https://i.ibb.co/N2pdqcqP/BIR.png",
"ميدلزبره": "https://www8.0zz0.com/2022/03/19/02/178476248.png",
"واتفورد": "https://www12.0zz0.com/2022/04/23/14/480692918.png",
"نوريتش": "https://www10.0zz0.com/2022/04/16/00/166549494.png",  
 "العروبة": "https://i.ibb.co/3HWcQd0/ORO.png",
"الزلفي": "https://i.ibb.co/Ng7jYjfh/ZUL.png",
"البكيرية": "https://i.ibb.co/HD1qKX4N/BUK.png",
"جدة": "https://i.ibb.co/cSwsRjJf/JED.png",
"الجبيل": "https://i.ibb.co/ccFwMbSs/JBY.png", 
"العـربي": "https://i.ibb.co/6R61BJ1/arabi-ksa.png",
"الباطن": "https://albatin.sa/wp-content/uploads/2021/10/cropped-%D8%B9%D8%B1%D8%A8%D9%8A-300x289.png",
"الرائد": "https://www12.0zz0.com/2022/03/19/02/141642162.png",
"الفيصلي": "https://i.ibb.co/xLjJCLq/image.png",
"الطائي": "https://i.ibb.co/swQzdM7/Altai.png",
"أبها": "https://www.saff.com.sa/uploadcenter/saffteamlarge1667133437.png",
"العدالة": "https://i.ibb.co/stg9NQW/aLadaLah.png",
"الجبلين": "https://i.ibb.co/bKm21J5/image.png",
"الوحـدة": "https://i.ibb.co/bXN1J3D/ALWEHDA.png",
"كوبنهاغن": "https://i.ibb.co/h9P9jJh/Kobenhavn.png",
"سيلتك": "https://i.ibb.co/16Wq1tH/CELTIC.png",
"فنربخشة": "https://i.ibb.co/fd305p9G/FEN.png",
"غراتس": "https://i.ibb.co/b5mwG8zd/SGR.png",
"بودو غليمت": "https://i.ibb.co/84R2nf4H/BOD.png",
"بازل": "https://i.ibb.co/mC1zq5nT/BFC.png",
"كيرات": "https://i.ibb.co/kgsk9RSw/KAR.png",
"الحزم": "https://i.ibb.co/QfbBfqq/image.png",
"النجمة": "https://i.ibb.co/9LWJCmS/NAG.png",
"نيوم": "https://i.ibb.co/ccHW5wYz/NEOM.png",
"المنستيري": "https://i.ibb.co/93Zvzq0N/USM.png",
"سباهان": "https://i.ibb.co/Qjr19KPQ/SBH.png",
"وادي دجلة": "https://i.ibb.co/ksLnVqxs/DEG.png",
"مونزا": "https://i.ibb.co/qYkJg8NF/MONZA.png",
"تيرول": "https://i.ibb.co/bMs5QMww/TIROL.png",
"آلكمار": "https://i.ibb.co/gT5D2T4/AZ.png",
"نيميخن": "https://www12.0zz0.com/2022/04/23/14/949700172.png",
"فاينورد": "https://i.ibb.co/3yHKZGs4/FEY.png",
"أياكس": "https://i.ibb.co/xt3rPJQr/AJAX.png",
"إكسيلسيور": "https://i.ibb.co/27BWP9pw/EXC.png",
"غرونينغن": "https://i.ibb.co/3yM1Gmzr/GRN.png",
"سبارتا": "https://i.ibb.co/XfGbhsfN/SPR.png",
"أوترخت": "https://i.ibb.co/PsGXrd2w/UTR.png",
"هيراكليس": "https://i.ibb.co/YTZ5myX2/HER.png",
"هيرينفين": "https://i.ibb.co/xKvFBzTj/HEE.png",
"زفوله": "https://i.ibb.co/qLkDpjq6/PEC.png",
"تلستار": "https://i.ibb.co/nN15B2T2/TEL.png",
"فورتونا": "https://i.ibb.co/6c80QG3n/FOR.png",
"تفينتي": "https://i.ibb.co/DH4bdTkb/TWE.png",
"فولندام": "https://i.ibb.co/Fk7y8GFh/VOL.png",
"ناك بريدا": "https://i.ibb.co/XZHtYRm6/NAC.png",
"جو أهيد": "https://i.ibb.co/Vc7fQ6Y1/AHE.png",
"آيندهوفن": "https://i.ibb.co/6bmZ1gF/PSV.png",
"الكوكب": "https://i.ibb.co/PpmgX69/KM.png",
"الكوكب": "https://i.ibb.co/PpmgX69/KM.png",
"الفتح الرباطي": "https://i.ibb.co/CKMG7HJ/FUS.png",
"آسفي": "https://i.ibb.co/Jp0k8wj/OCS.png",
"توارݣة": "https://i.ibb.co/x7yj1f3/TOUARGA.png",
"النادي المكناسي": "https://i.ibb.co/m5SYTT4m/CODM.png",
"حسنية أكادير": "https://i.ibb.co/qYMsRMTB/HUSA.png",
"الدشيرة": "https://i.ibb.co/hx4dRVYJ/OD.png",
"الدفاع الجديدي": "https://i.ibb.co/0RBDdSQ7/DHJ.png",
"يوكوهاما": "https://i.ibb.co/5x1w2p8d/Yoko.png",
"لوتن تاون": "https://i.ibb.co/6gWsbzR/LUTON.png",
"كازاخستان": "https://s3.eu-west-2.amazonaws.com/qmasters/flags/png/kazakhstan/flag-3d-round-250.png",
"ويلز": "https://cdn.countryflags.com/thumbs/wales/flag-3d-round-250.png",
"ليتوانيا": "https://cdn.countryflags.com/thumbs/lithuania/flag-3d-round-500.png",
"مالطا": "https://cdn.countryflags.com/thumbs/malta/flag-3d-round-500.png",
"جورجيا": "https://cdn.countryflags.com/thumbs/georgia/flag-3d-round-500.png",
"تركيا": "https://cdn.countryflags.com/thumbs/turkey/flag-3d-round-500.png",
"ليختنشتاين": "https://cdn.countryflags.com/thumbs/liechtenstein/flag-3d-round-500.png",
"بلجيكا": "https://cdn.countryflags.com/thumbs/belgium/flag-3d-round-500.png",
"هولندا": "https://cdn.countryflags.com/thumbs/netherlands/flag-3d-round-500.png",
"بولندا": "https://cdn.countryflags.com/thumbs/poland/flag-3d-round-500.png",
"لوكسمبورج": "https://cdn.countryflags.com/thumbs/luxembourg/flag-3d-round-500.png",
"أيرلندا ش": "https://cdn.countryflags.com/thumbs/northern-ireland/flag-3d-round-500.png",
"سلوفاكيا": "https://cdn.countryflags.com/thumbs/slovakia/flag-3d-round-500.png",
"سلوفينيا": "https://cdn.countryflags.com/thumbs/slovenia/flag-3d-round-500.png",
"بلغاريا": "https://cdn.countryflags.com/thumbs/bulgaria/flag-3d-round-500.png",
"تشيكيا": "https://cdn.countryflags.com/thumbs/czech-republic/flag-3d-round-500.png",
"السويد": "https://cdn.countryflags.com/thumbs/sweden/flag-3d-round-500.png",
"سويسرا": "https://cdn.countryflags.com/thumbs/switzerland/flag-3d-round-500.png",
"كوسوفو": "https://cdn.countryflags.com/thumbs/kosovo/flag-3d-round-500.png",
"إسكتلندا": "https://cdn.countryflags.com/thumbs/scotland/flag-3d-round-500.png",
"الدنمارك": "https://cdn.countryflags.com/thumbs/denmark/flag-3d-round-500.png",
"اليونان": "https://cdn.countryflags.com/thumbs/greece/flag-3d-round-500.png",
"بيلاروسيا": "https://cdn.countryflags.com/thumbs/belarus/flag-3d-round-500.png",
"أيسلندا": "https://cdn.countryflags.com/thumbs/iceland/flag-3d-round-500.png",
"أذربيجان": "https://cdn.countryflags.com/thumbs/azerbaijan/flag-3d-round-500.png",
"أوكرانيا": "https://cdn.countryflags.com/thumbs/ukraine/flag-3d-round-500.png",
"فرنسا": "https://cdn.countryflags.com/thumbs/france/flag-3d-round-500.png",
"إيطاليا": "https://cdn.countryflags.com/thumbs/italy/flag-3d-round-500.png",
"إستونيا": "https://cdn.countryflags.com/thumbs/estonia/flag-3d-round-500.png",
"مولدوفا": "https://cdn.countryflags.com/thumbs/moldova/flag-3d-round-500.png",
"جزر فارو": "https://cdn.countryflags.com/thumbs/faroe-islands/flag-3d-round-500.png",
"كرواتيا": "https://cdn.countryflags.com/thumbs/croatia/flag-3d-round-500.png",
"لاتفيا": "https://cdn.countryflags.com/thumbs/latvia/flag-3d-round-500.png",
"صربيا": "https://cdn.countryflags.com/thumbs/serbia/flag-3d-round-500.png",
"فنلندا": "https://cdn.countryflags.com/thumbs/finland/flag-3d-round-500.png",
"أرمينيا": "https://cdn.countryflags.com/thumbs/armenia/flag-3d-round-500.png",
"البرتغال": "https://cdn.countryflags.com/thumbs/portugal/flag-3d-round-500.png",
"أندورا": "https://cdn.countryflags.com/thumbs/andorra/flag-3d-round-500.png",
"أيرلندا": "https://cdn.countryflags.com/thumbs/ireland/flag-3d-round-500.png",
"المجر": "https://cdn.countryflags.com/thumbs/hungary/flag-3d-round-500.png",
"النمسا": "https://cdn.countryflags.com/thumbs/austria/flag-3d-round-250.png",
"قبرص": "https://cdn.countryflags.com/thumbs/cyprus/flag-3d-round-500.png",
"سان مارينو": "https://cdn.countryflags.com/thumbs/san-marino/flag-3d-round-500.png",
"البوسنة": "https://cdn.countryflags.com/thumbs/bosnia-and-herzegovina/flag-3d-round-500.png",
"جبل طارق": "https://i.ibb.co/99V6KX2j/Gibralta.png",
"مقدونيا ش": "https://cdn.countryflags.com/thumbs/north-macedonia/flag-3d-round-500.png",
"ألبانيا": "https://cdn.countryflags.com/thumbs/albania/flag-3d-round-500.png",
"مونتينيغرو": "https://cdn.countryflags.com/thumbs/montenegro/flag-3d-round-500.png",
    "غرناطة": "https://i.ibb.co/Ld5HY0D0/Granada.png",  
"شباب الأهلي": "https://i.ibb.co/w4V8JTx/Sha-alah-Li.png",
"الظفرة": "https://i.ibb.co/8MWGxcy/aLdhafra.png",
"الجزيرة": "https://i.ibb.co/2qBcB8C/aLJazira.png",
"الوحدة": "https://www.as-goal.com/wp-content/uploads/2020/11/uni_al_wahda_v2-e1606403444577.png",
"الوصل": "https://i.ibb.co/fGRjCr9/ALWASL.png",
"دبا الفجيرة": "https://i.ibb.co/0pgk4Tm3/DIBBA.png",
"النصـر": "https://uae-proleague.s3.me-south-1.amazonaws.com/uploads/team/images/logoL_250542630.png",
"كلباء": "https://uae-proleague.s3.me-south-1.amazonaws.com/uploads/team/images/logoL_1012842572.png",
"عجمان": "https://i.ibb.co/Hr4dNQ0/Ajman.png",
"بني ياس": "https://www12.0zz0.com/2022/03/15/01/815151411.png",
"الشارقة": "https://uae-proleague.s3.me-south-1.amazonaws.com/uploads/team/images/logoL_1463264784.png",
"خورفكان": "https://www11.0zz0.com/2022/05/17/00/579210153.png",
"البطائح": "https://i.ibb.co/b2ydq68/Al-Bataeh.png",
"لشبونة": "https://ssl.gstatic.com/onebox/media/sports/logos/58doDuhR0wW3WZE9PdODUw_96x96.png",
"ميلان":"https://i.ibb.co/r50Jqt0/ACM.png",
"الإتحاد": "https://www5.0zz0.com/2022/03/07/23/196011317.png",
"النصر": "https://i.ibb.co/7dzdnSW5/NASSR.png",
"الأهـلي": "https://i.ibb.co/0RF7RS76/AHLI.png",
"الشباب": "https://i.ibb.co/8D04Pmz5/SHABAB.png",
"الإتفاق": "https://i.ibb.co/Rh5pLtr/ettifaQ.png",
"التعاون": "https://i.ibb.co/t8zWdFr/a-Ltaawoun.png",
"الفتح": "https://i.ibb.co/8cW0sts/Fateh.png",
"الخليج": "https://i.ibb.co/H2zTD61/KHALEEJ.png",
"الفيحاء": "https://i.ibb.co/YN61dh8/ALFATHA.png",
"ضمك": "https://i.ibb.co/0yp7KSV/damac.png",
"الرياض": "https://i.ibb.co/LXDMbsfS/RIYADH.png",
"الأخدود": "https://i.ibb.co/ymgfmB55/OKHDOD.png",
"الخلود": "https://i.ibb.co/zTKtPdyr/KHL.png",
"القادسية": "https://i.ibb.co/DPSR74Q5/Qadisiya.png",
"يعقوب المنصور": "https://i.ibb.co/4RnZDdrr/USYM.png",
"فلسطين": "https://i.ibb.co/pyNJ41x/palestine.png",
"اليمن": "https://i.ibb.co/RNMkr6d/yemen.png",
"عمان": "https://i.ibb.co/nzGpGwg/Oman.png",
"سوريا": "https://i.ibb.co/0px6T1Sb/Syria.png",
"لبنان": "https://i.ibb.co/W3TJ2vN/lebanon.png",
"البحرين": "https://i.ibb.co/Yy8j0Rw/bahrain.png",
"الكويت": "https://i.ibb.co/LS5HkDS/kuwait.png",
"السعودية": "https://i.ibb.co/8sv6Wm6/saudi.png",
"العراق": "https://i.ibb.co/4Rqzqf4/iraq.png",
"الإمارات": "https://i.ibb.co/P5pBHnQ/emirates.png",
"قطر": "https://i.ibb.co/qRKjXjX/Qatar.png",
"الأردن": "https://i.ibb.co/j6Hv8tS/jordan.png",
"جيرونا": "https://i.ibb.co/nMmCs88y/GIR.png",
"إشبيلية": "https://i.ibb.co/C6zqYm8/Seville.png",
"خيتافي": "https://www.as-goal.com/wp-content/uploads/2020/11/spa_getafe-e1606400203470.png",
"أتلتيك بلباو": "https://i.ibb.co/jYty20r/BILBAO.png",
"رايو فاليكانو": "https://www3.0zz0.com/2022/03/19/02/899011854.png",
"أوساسونا": "https://www.as-goal.com/wp-content/uploads/2020/12/%D8%A7%D9%88%D8%B3%D8%A7%D8%B3%D9%88%D9%86%D8%A7.png",
"ريال سوسيداد": "https://i.ibb.co/CswCX9n/sociedad.png",
"ريال بيتيس": "https://www.as-goal.com/wp-content/uploads/2020/12/%D8%B1%D9%8A%D8%A7%D9%84-%D8%A8%D9%8A%D8%AA%D9%8A%D8%B3.png",
"ريال مايوركا": "https://www.as-goal.com/wp-content/uploads/2021/09/2000333-1.png",
"ألافيس": "https://i.ibb.co/b586tZFV/Alaves.png",
"سيلتا فيغو": "https://i.ibb.co/HDkL3jt/S-T-V.png",
"فياريال": "https://www.as-goal.com/wp-content/uploads/2020/11/spa_villarreal-e1606400321662.png",
"فالنسيا": "https://i.ibb.co/g7KJB3X/VALENCIA.png",
"ليفانتي": "https://ssl.gstatic.com/onebox/media/sports/logos/SQB-jlVosxVV1Ce79FhbOA_96x96.png",
"إسبانيول": "https://i.ibb.co/QjQQDwJh/ESP.png",
"إلتشي": "https://www10.0zz0.com/2022/03/19/01/921675333.png",
"ريال أوفييدو": "https://i.ibb.co/4ZkbDdHJ/FO.png",
"أمريكا": "https://cdn.countryflags.com/thumbs/united-states-of-america/flag-3d-round-500.png",
"المكسيك": "https://cdn.countryflags.com/thumbs/mexico/flag-3d-round-500.png",
"نادي قطر": "https://i.ibb.co/Gf25TTHs/QAT.png",
"أم صلال": "https://i.ibb.co/nMTnsthg/UMM-SALAL.png",
"الشمال": "https://i.ibb.co/gFDvs91K/ALSHAMAL.png",
"الأهــلي": "https://i.ibb.co/MkP7Gdbv/ALAHLI.png",
"الشحانية": "https://i.ibb.co/YzhkVmD/SHAHANIA.png",
"السيلية": "https://i.ibb.co/PvQs0f1B/SAL.png",
"العربي": "https://i.ibb.co/5XqkScfm/ALARABI.png",
"الوكرة": "https://i.ibb.co/1fQMmPm2/WAKRAH.png",
"السد": "https://i.ibb.co/tw024QKc/SAD.png",
"الدحيل": "https://www2.0zz0.com/2022/03/13/23/787781331.png",
"الريان": "https://i.ibb.co/2PnKXZD/AlRayyan.png",
"الغرافة": "https://i.ibb.co/594Ggbk/Al-Gharrafa.png",
"إريتريا": "https://i.ibb.co/4gjfWG5/eritrea.png",
"توجو": "https://cdn.countryflags.com/thumbs/togo/flag-3d-round-500.png",
"جامبيا": "https://cdn.countryflags.com/thumbs/gambia/flag-3d-round-500.png",
"مالي": "https://cdn.countryflags.com/thumbs/mali/flag-3d-round-500.png",
"إتحاد العاصمة": "https://cdn.sportfeeds.io/sdl/images/team/crest/large/8yto6v12sv1yrpg8ad5eaq62c.png",
"شباب بلوزداد": "https://www8.0zz0.com/2022/03/19/02/369702279.png",
"باراجواي": "https://s3.eu-west-2.amazonaws.com/qmasters/flags/png/paraguay/flag-3d-round-250.png",
"الإكوادور": "https://i.ibb.co/fkRBvKP/ecuador.png",
"أوروغواي": "https://cdn.countryflags.com/thumbs/uruguay/flag-3d-round-500.png",
"بيرو": "https://cdn.countryflags.com/thumbs/peru/flag-3d-round-500.png",
"الأرجنتين": "https://cdn.countryflags.com/thumbs/argentina/flag-3d-round-500.png",
"فنزويلا": "https://cdn.countryflags.com/thumbs/venezuela/flag-3d-round-500.png",
"البرازيل": "https://i.ibb.co/RjjWwr1/brazil.png",
"تشيلي": "https://cdn.countryflags.com/thumbs/chile/flag-3d-round-500.png",
"كولومبيا": "https://cdn.countryflags.com/thumbs/colombia/flag-3d-round-500.png",
"بوليفيا": "https://cdn.countryflags.com/thumbs/bolivia/flag-3d-round-500.png",
"مصر": "https://i.ibb.co/Gkv1MZm/egypt.png",
"بوركينا فاسو": "https://cdn.countryflags.com/thumbs/burkina-faso/flag-3d-round-500.png",
"سيراليون": "https://cdn.countryflags.com/thumbs/sierra-leone/flag-3d-round-500.png",
"إثيوبيا": "https://cdn.countryflags.com/thumbs/ethiopia/flag-3d-round-500.png",
"غينيا بيساو": "https://cdn.countryflags.com/thumbs/guinea-bissau/flag-3d-round-500.png",
"جيبوتي": "https://cdn.countryflags.com/thumbs/djibouti/flag-3d-round-500.png",
"الكونغو د": "https://cdn.countryflags.com/thumbs/congo-democratic-republic-of-the/flag-3d-round-500.png",
"السنغال": "https://cdn.countryflags.com/thumbs/senegal/flag-3d-round-500.png",
"السودان": "https://i.ibb.co/MNWWPg0/sudan.png",
"ج السودان": "https://i.ibb.co/FsF3cJF/south-sudan.png",
"توغو": "https://cdn.countryflags.com/thumbs/togo/flag-3d-round-500.png",
"موريتانيا": "https://i.ibb.co/pQvB67f/mauritania.png",
"ج أفريقيا": "https://cdn.countryflags.com/thumbs/south-africa/flag-3d-round-500.png",
"رواندا": "https://cdn.countryflags.com/thumbs/rwanda/flag-3d-round-500.png",
"بنين": "https://cdn.countryflags.com/thumbs/benin/flag-3d-round-500.png",
"نيجيريا": "https://cdn.countryflags.com/thumbs/nigeria/flag-3d-round-500.png",
"ليسوتو": "https://cdn.countryflags.com/thumbs/lesotho/flag-3d-round-500.png",
"زيمبابوي": "https://cdn.countryflags.com/thumbs/zimbabwe/flag-3d-round-500.png",
"الرأس الأخضر": "https://cdn.countryflags.com/thumbs/cape-verde/flag-3d-round-500.png",
"الكاميرون": "https://cdn.countryflags.com/thumbs/cameroon/flag-3d-round-500.png",
"ليبيا": "https://i.ibb.co/6nHnP71/libya.png",
"أنغولا": "https://cdn.countryflags.com/thumbs/angola/flag-3d-round-500.png",
"موريشيوس": "https://cdn.countryflags.com/thumbs/mauritius/flag-3d-round-500.png",
"إسواتيني": "https://cdn.countryflags.com/thumbs/swaziland/flag-3d-round-500.png",
"تنزانيا": "https://cdn.countryflags.com/thumbs/tanzania/flag-3d-round-500.png",
"زامبيا": "https://cdn.countryflags.com/thumbs/zambia/flag-3d-round-500.png",
"النيجر": "https://cdn.countryflags.com/thumbs/niger/flag-3d-round-500.png",
"الكونغو": "https://i.ibb.co/xh3T36V/congo.png",
"ساحل العاج": "https://cdn.countryflags.com/thumbs/cote-d-ivoire/flag-3d-round-500.png",
"الغابون": "https://cdn.countryflags.com/thumbs/gabon/flag-3d-round-500.png",
"بوروندي": "https://cdn.countryflags.com/thumbs/burundi/flag-3d-round-500.png",
"كينيا": "https://cdn.countryflags.com/thumbs/kenya/flag-3d-round-500.png",
"غامبيا": "https://cdn.countryflags.com/thumbs/gambia/flag-3d-round-500.png",
"سيشل": "https://cdn.countryflags.com/thumbs/seychelles/flag-3d-round-500.png",
"الجزائر": "https://i.ibb.co/txDFnwY/algeria.png",
"موزمبيق": "https://cdn.countryflags.com/thumbs/mozambique/flag-3d-round-500.png",
"بوتسوانا": "https://cdn.countryflags.com/thumbs/botswana/flag-3d-round-500.png",
"أوغندا": "https://cdn.countryflags.com/thumbs/uganda/flag-3d-round-500.png",
"غينيا": "https://cdn.countryflags.com/thumbs/guinea/flag-3d-round-500.png",
"غ الإستوائية": "https://cdn.countryflags.com/thumbs/equatorial-guinea/flag-3d-round-500.png",
"الصومال": "https://cdn.countryflags.com/thumbs/somalia/flag-3d-round-500.png",
"تونس": "https://i.ibb.co/Hxc7J93/tunisia.png",
"ناميبيا": "https://cdn.countryflags.com/thumbs/namibia/flag-3d-round-500.png",
"ليبيريا": "https://i.ibb.co/Y2ZdJxp/liberia.png",
"مالاوي": "https://cdn.countryflags.com/thumbs/malawi/flag-3d-round-500.png",
"ساو تومي": "https://cdn.countryflags.com/thumbs/sao-tome-and-principe/flag-3d-round-500.png",
"غانا": "https://cdn.countryflags.com/thumbs/ghana/flag-3d-round-500.png",
"جزر القمر": "https://cdn.countryflags.com/thumbs/comoros/flag-3d-round-500.png",
"مدغشقر": "https://cdn.countryflags.com/thumbs/madagascar/flag-3d-round-500.png",
"أفريقيا و": "https://cdn.countryflags.com/thumbs/central-african-republic/flag-3d-round-500.png",
"تشاد": "https://i.ibb.co/g9RZRkD/chad.png",
"يونيون برلين": "https://i.ibb.co/MCH4N4m/UNION.png",
"باير ليفركوزن": "https://i.ibb.co/sqqdtKv/Leverkusen.png",
"هوفنهايم": "https://i.ibb.co/TD5mDH8K/Hoffenheim.png",
"فرايبورج": "https://i.ibb.co/fcwGTfj/Freiburg.png",
"أوجسبورج": "https://i.ibb.co/V0xwfbsw/Augsburg.png",
"فيردر بريمن": "https://i.ibb.co/vCXj6vVx/Bremen.png",
"فولفسبورج": "https://i.ibb.co/HTyV4cdk/Wolfsburg.png",
"كولن": "https://i.ibb.co/DHjFpHsR/Coln.png",
"مونشنغلادباخ": "https://i.ibb.co/WNZCh43h/Gladbach.png",
"فرانكفورت": "https://i.ibb.co/hRmQzvx7/Frankfurt.png",
"ماينتس": "https://i.ibb.co/9mSjRPcg/Mainz.png",
"شتوتجارت": "https://i.ibb.co/yn4npMYy/Stuttgart.png",
"هايدنهايم": "https://i.ibb.co/hxGgjjdt/Heidenheim.png",
"لايبزيج": "https://i.ibb.co/CK3d7Lm6/Leipzig.png",
"هامبورج": "https://i.ibb.co/fz35wPBy/Hamburg.png",
"سانت باولي": "https://i.ibb.co/JWCwDwpg/Pauli.png",
"سياتل": "https://i.ibb.co/7JspzskK/Seattle.png",
"نهضة بركان": "https://i.ibb.co/m9qSHjS/BERKANE.png",
"أولمبيك أسفي": "https://i.ibb.co/Jp0k8wj/OCS.png",
"أسفي": "https://i.ibb.co/Jp0k8wj/OCS.png",
"بركان": "https://i.ibb.co/m9qSHjS/BERKANE.png",
"المغرب الفاسي": "https://i.ibb.co/jkYmhW9/MAS.png",
"إتحاد توارݣة": "https://i.ibb.co/x7yj1f3/TOUARGA.png",
"إتحاد طنجة": "https://i.ibb.co/GQ2xbp0/TANGER.png",
"الفتح الرياضي": "https://i.ibb.co/CKMG7HJ/FUS.png",
"الجيش الملكي": "https://i.ibb.co/gMWfwyx/image.png",
"المغرب": "https://i.ibb.co/GWT9SFk/morocco.png",
"لانس": "https://i.ibb.co/x2Rm8X0/LENS.png",
"الرجاء": "https://i.ibb.co/vQMTR4R/Raja.png",
"نهضة الزمامرة": "https://i.ibb.co/ydHvNcZ/ZEMAMRA.png",
"شباب السوالم": "https://i.ibb.co/RNNrKQt/SOUALEM.png",
"مولودية وجدة": "https://i.ibb.co/jDBwLpB/MCO.png",
"شباب المحمدية": "https://i.ibb.co/VHfKcrh/SCCM.png",
"أولمبيك خريبكة": "https://i.ibb.co/BLg4DgL/OCK.png",
"نادي باريس": "https://i.ibb.co/M5QG3QPf/PARIS.png",
"نانت": "https://www9.0zz0.com/2022/03/12/03/972251609.png",
"نيس": "https://i.ibb.co/hytw2BG/OGC-NICE.png",
"تولوز": "https://i.ibb.co/B6FvdLM/TOULOUSE.png",
"رين": "https://i.ibb.co/y0CCKX4/RENNAIS.png",
"مارسيليا": "https://www7.0zz0.com/2022/03/05/22/573594235.png",
"أوكسير": "https://i.ibb.co/0KB9Y2c/A-J-AUXERRE.png",
"لوريان": "https://www13.0zz0.com/2022/05/08/01/370110752.png",
"بريست": "https://i.ibb.co/59b1cQG/SB29.png",
"ليل": "https://www13.0zz0.com/2022/03/19/02/411526042.png",
"لانس": "https://i.ibb.co/x2Rm8X0/LENS.png",
"ليون": "https://www5.0zz0.com/2022/03/08/22/211576708.png", 
"ميتز": "https://www14.0zz0.com/2022/05/20/23/923570602.png",
"ستراسبورج": "https://i.ibb.co/tP3d44X4/Strasbourg.png",
"لوهافر": "https://i.ibb.co/LzwNx5yQ/HAC.png",
"أنجيه": "https://i.ibb.co/W4qvMwgx/SCO.png",
"موناكو": "https://i.ibb.co/DdSvNxF/MONACO.png",
"الريال": "https://i.ibb.co/tpNR0sfR/riyal.png",
"ريال مدريد": "https://i.ibb.co/tpNR0sfR/riyal.png",
"برشلونة": "https://i.ibb.co/Fb38D5Gt/FCB.png",
"سالزبورج": "https://i.ibb.co/DRLdPsG/R-B-SBG.png",
"الهلال": "https://i.ibb.co/Ry3chpp/ALhilale.png",
"باتشوكا": "https://i.ibb.co/1J2fzS6H/Pachuca.png",
"بوتافوغو": "https://i.ibb.co/4Z2YftvC/Botafogo.png",
"إنجلترا": "https://i.ibb.co/KxXGPN9/england.png",
"ألمانيا": "https://cdn.countryflags.com/thumbs/germany/flag-3d-round-500.png",
"باريس": "https://i.ibb.co/mN4Sf23/PSG.png",
"هولندا": "https://cdn.countryflags.com/thumbs/netherlands/flag-3d-round-500.png",
"إسبانيا": "https://i.ibb.co/vwn876G/spain.png",
"السيتي": "https://i.ibb.co/7g8f9XY/MAN-CITY.png", 
"بيرنلي": "https://i.ibb.co/SD83htD2/BRNLY.png",
"ليفربول": "https://i.ibb.co/7xY2hc83/LFC.png",
"تشيلسي": "https://www.as-goal.com/wp-content/uploads/2022/12/49.png",
"مان سيتي": "https://i.ibb.co/7g8f9XY/MAN-CITY.png",
"مان يونايتد": "https://i.ibb.co/cw4KRvD/Man-united.png",
"مانشستر سيتي": "https://i.ibb.co/7g8f9XY/MAN-CITY.png",
"مانشستر يونايتد": "https://i.ibb.co/cw4KRvD/Man-united.png",
"توتنهام": "https://i.ibb.co/8gNxhW58/TOT.png",
"وولفرهامبتون": "https://www.as-goal.com/wp-content/uploads/2020/11/eng_wolverhampton_wanderers-e1606399777618.png",
"وست هام": "https://www6.0zz0.com/2022/03/17/08/454380681.png",
"إيفرتون": "https://www.as-goal.com/wp-content/uploads/2020/11/eng_everton-e1606399678651.png",
"بورنموث": "https://i.ibb.co/Tqk9HdFf/BOURNEMOUTH.png",
"أرسنال": "https://i.ibb.co/WcW9hBy/Arsenal.png",
"كريستال بالاس": "https://i.ibb.co/qgcVQmZ/Crystal-Palace.png",
"فولهام": "https://i.ibb.co/Pg2M4nr/FFC.png",
"برينتفورد": "https://i.ibb.co/FkFtQFPR/Brentford.png",
"أتلتيكو مدريد": "https://i.ibb.co/QPcHWRm/Atletico-Madrid.png",
"نوتنغهام": "https://i.ibb.co/BVQjFbxy/FOREST.png",
"برايتون": "https://i.ibb.co/39WrBpqx/Brighton.png",
"سندرلاند": "https://i.ibb.co/qMCzrPhr/Sunderland.png",
"أستون فيلا": "https://i.ibb.co/gLj831yS/ASTON.png",
"الترجي": "https://i.ibb.co/ZRMn8PhH/TARAJI.png",
"لوس أنجلوس": "https://i.ibb.co/CpVYfVbd/Angeles.png",
"فلامنجو": "https://i.ibb.co/3Kjs6wf/Flamingo.png",
"صن داونز": "https://i.ibb.co/FYd071B/SUNDOWNS.png",
"فلومنينسي": "https://i.ibb.co/p6x8yRgH/Fluminense.png",
"فلومينينسي": "https://i.ibb.co/p6x8yRgH/Fluminense.png",
"دورتموند": "https://i.ibb.co/gZMynLtV/BVB.png",
"أولسان": "https://i.ibb.co/nqtsNvqc/ulsan.png",
"إنتر ميلان": "https://i.ibb.co/bQ1thpg/intermilan.png",
"ريفر بليت": "https://i.ibb.co/spHc8SR2/River-Plate.png",
"أوراوا رد": "https://i.ibb.co/hRXhBd6t/Urawa-Red.png",
"يوفنتوس": "https://i.ibb.co/DgjwxhzY/JOV.png",
"الوداد": "https://i.ibb.co/pvKBM2t/WAC.png",
"مونتيري": "https://i.ibb.co/r2rrZ1GR/Monterey.png",
"العين": "https://i.ibb.co/58GSxrL/ALAIN.png",
"نيوكاسل": "https://www6.0zz0.com/2022/04/17/14/499143569.png",
"ليدز يونايتد": "https://i.ibb.co/CP16Dfb/leeds-united.png",
"بورتو": "https://i.ibb.co/j6Mj2Z9/PORTO.png",
"الأهلي": "https://i.ibb.co/NY3x1RZ/ALAHLY.png",
"إنتر ميامي": "https://i.ibb.co/Fbz2FqcD/Inter-Miami.png",
"بالميراس": "https://i.ibb.co/v4bqkC4s/Palmeiras.png",
"بنفيكا": "https://i.ibb.co/Vp8b2WP/Benfica.png",
"بايرن ميونخ": "https://i.ibb.co/rcTJhKy/BAYERN.png",
"أوكلاند سيتي": "https://i.ibb.co/yFMKGrWm/Auckland.png",
"بوكا جونيورز": "https://i.ibb.co/93yqwHKk/CABJ.png",
"مايوركا": "https://www.as-goal.com/wp-content/uploads/2021/09/2000333-1.png",
"أتلتيك بيلباو": "https://i.ibb.co/jYty20r/BILBAO.png",
"البنزرتي": "https://i.ibb.co/ZRVMp7wj/CAB.png",
"نادي زد": "https://i.ibb.co/LPGLLX5/zed-fc.png",
"سيراميكا": "https://i.ibb.co/fv2T3CH/CFC.png",
"الإتحـاد": "https://i.ibb.co/7drk6WLw/ITT.png",
"المصري": "https://i.ibb.co/dMYM0Kz/PortSaid.png",
"الزمالك": "https://i.ibb.co/pjH1Tnj/zamalek-club.png",
"الجونة": "https://i.ibb.co/Jw77zSmh/GOUNA.png",
"مودرن": "https://i.ibb.co/6RRt3BWc/MOD.png",
"سموحة": "https://i.ibb.co/mFvJ1cWL/SMO.png",
"بيراميدز": "https://i.ibb.co/jWmYNbv/PYRAMIDS.png",
"البنك الأهلي": "https://i.ibb.co/7xcnqmbm/NBE.png",
"فاركو": "https://www2.0zz0.com/2022/03/17/08/249014132.png",
"طلائع الجيش": "https://i.ibb.co/dpZXw90/image.png",
"إنبي": "https://www12.0zz0.com/2022/03/16/03/814688782.png",
"غزل المحلة": "https://i.ibb.co/R48jFv3/image.png",
"الإسماعيلي": "https://i.ibb.co/k2yzDwLF/ISM.png",
"بتروجيت": "https://www2.0zz0.com/2022/03/12/03/828253820.png",
"حرس الحدود": "https://i.ibb.co/vxVm8p8G/HEC.png",
"المقاولون": "https://www9.0zz0.com/2022/03/16/03/929149194.png",
"كهرباء": "https://i.ibb.co/hxR0WtTg/IESC.png",
"رينجرز": "https://i.ibb.co/QRxkJ39/RAN.png",
"بروج": "https://i.ibb.co/XrYcsH0x/BRU.png",
"تشارلتون": "https://i.ibb.co/zhgfHY22/CHR.png",
"ليستر سيتي": "https://i.ibb.co/G3THy5Fn/LEI.png",
"مانسفيلد": "https://i.ibb.co/mnTJmzR/MFT.png"
,"أكسفورد": "https://i.ibb.co/TxyJCK5Z/OXF.png",
"غريمسبي": "https://i.ibb.co/fdPXdZdp/GRI.png",
"بريستول": "https://i.ibb.co/qYkFV3GD/BRI.png",

  }
};